### ISSUE TITLE
Just a question, lel

### ISSUE THREAD

**Issue by hatoving** [wildestwooder/funkin3ds#1]
Heyo, I have a question.
(I couldn't find a way to contact you so this is my best bet.)

Is this a recreation of some sort? Or is it a port of the original source code?
I'm interested in porting it for the PS Vita if the source code ever gets released.
(Note, all I've seen are crunched-down versions of FNF screenshots here on the repo so...)

Hope you answer. Ciao!
Best regards and take care,
-hat

**Comment by wildestwooder** [comment]
1. I'll most likely be releasing the source code soon! Just gonna finish it up first. I'm having some issues but I'm doing my best to get them fixed. Making sure to stick to my sources, clean up code, etc. 

2. This is a port of the game to 3DS, not a recreation. All of the source code was reworked. (If I'm guessing correctly, you could definitely rework it to work on PS Vita. Sorry about all the screenshots being scrunched, might organize my images better/get better images in general. Feeling as if I made it a bit too cluttered.

Thank you for reaching out though, hope this answers your questions! :]
